openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/users:
    get:
      summary: 'Get all users.'
      operationId: getAllUsers
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    current_page: 1
                    data: []
                    first_page_url: 'http://localhost/api/users?page=1'
                    from: null
                    last_page: 1
                    last_page_url: 'http://localhost/api/users?page=1'
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: 'http://localhost/api/users?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    next_page_url: null
                    path: 'http://localhost/api/users'
                    per_page: 10
                    prev_page_url: null
                    to: null
                    total: 0
                  message: 'Users retrieved successfully.'
                properties:
                  data:
                    type: object
                    properties:
                      current_page:
                        type: integer
                        example: 1
                      data:
                        type: array
                        example: []
                      first_page_url:
                        type: string
                        example: 'http://localhost/api/users?page=1'
                      from:
                        type: string
                        example: null
                      last_page:
                        type: integer
                        example: 1
                      last_page_url:
                        type: string
                        example: 'http://localhost/api/users?page=1'
                      links:
                        type: array
                        example:
                          -
                            url: null
                            label: '&laquo; Previous'
                            active: false
                          -
                            url: 'http://localhost/api/users?page=1'
                            label: '1'
                            active: true
                          -
                            url: null
                            label: 'Next &raquo;'
                            active: false
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              example: null
                            label:
                              type: string
                              example: '&laquo; Previous'
                            active:
                              type: boolean
                              example: false
                      next_page_url:
                        type: string
                        example: null
                      path:
                        type: string
                        example: 'http://localhost/api/users'
                      per_page:
                        type: integer
                        example: 10
                      prev_page_url:
                        type: string
                        example: null
                      to:
                        type: string
                        example: null
                      total:
                        type: integer
                        example: 0
                  message:
                    type: string
                    example: 'Users retrieved successfully.'
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Create a new user.'
      operationId: createANewUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/users/{id}':
    get:
      summary: ''
      operationId: getApiUsersId
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'User not found.'
                  errors: []
                properties:
                  message:
                    type: string
                    example: 'User not found.'
                  errors:
                    type: array
                    example: []
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiUsersId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiUsersId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the user.'
        example: 20
        required: true
        schema:
          type: integer
  /api/roles:
    get:
      summary: ''
      operationId: getApiRoles
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data: []
                  message: 'Roles retrieved successfully.'
                properties:
                  data:
                    type: array
                    example: []
                  message:
                    type: string
                    example: 'Roles retrieved successfully.'
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiRoles
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/roles/{id}':
    get:
      summary: ''
      operationId: getApiRolesId
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Role not found.'
                  errors: []
                properties:
                  message:
                    type: string
                    example: 'Role not found.'
                  errors:
                    type: array
                    example: []
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiRolesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiRolesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the role.'
        example: 19
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
